### ISSUE TITLE
Allow to modify tier parameters after creation

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#104]
In UI:
On setup a tier step. For each tier:
- add a radio button to each tier "Allow modifying". By default is off
- add Lorem ipsum description for radio button

if the switch is on, tier created with a method to update parameters of the tier such as 
- cap
- rate
- start date
- end date

**Comment by vbaranov** [comment]
Tier-contract:
setStartsAt(time:uint256)
setEndsAt(time:uint256)
setMaximumSellableTokens(tokens:uint256)

PricingStrategy-contract:
updateRate(newOneTokenInWei:uint256)
