### ISSUE TITLE
ABI is unusable after copying from generated document

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#114]
ABI is unusable after copying from generated PDF
Example,
generated document
https://transfer.sh/4d0z7/crowdsale.pdf
contract
0x820C6cfEbd22D1bd8C55f9527d1270BEe3bea7A9

not recognized by parity as a valid JSON array
![image](https://user-images.githubusercontent.com/424628/30081805-6f45af4c-923d-11e7-9e2d-7965f11abf9a.png)

Maybe we should switch from PDF to something else, e.g. anonymous Gist
https://developer.github.com/v3/gists/#create-a-gist

**Comment by rstormsf** [comment]
I like the idea for anon gists.

**Comment by igorbarinov** [comment]
@rstormsf Me too. PDF is proprietary. But it's client side with PDF. And with Gist it's serverless but not client side.

**Comment by rstormsf** [comment]
Hmm.  how about storing it into IndexedDB on the client side, so the user can always get back to it using his client's db?

**Comment by igorbarinov** [comment]
@rstormsf I'm using multiple computers and browsers and hundreds of contracts. I prefer to download or to bookmark

**Comment by rstormsf** [comment]
if that's the requirement, you should prob do gists

**Comment by igorbarinov** [comment]
@rstormsf maybe flat text files will work better?

**Comment by 15chrjef** [comment]
Generated Txt file. lmk your thoughts @vbaranov @igorbarinov

**Comment by vbaranov** [comment]
Example of generated txt file is attached
[contractInfo.txt](https://github.com/oraclesorg/ico-wizard/files/1298984/contractInfo.txt)
I like this flat text file solution. The content is usable to verify contract at Etherscan in this case.
