### ISSUE TITLE
Store parameters of crowdsales in a local file for Invest page

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#133]
An attacker can send a user to a legit website with a fraudulent contract. Crowdsale addresses now in GET parameters in URL and it's easy to commit fraud for the attacker.

One solution to mitigate the problem is to store parameters of the crowdsale in a configuration file. I propose to store them in local structure of an instance of ICO Wizard, e.g. using this technique https://stackoverflow.com/questions/37066758/how-can-i-use-a-config-file-in-react

If a file with config is present, the app should use parameters from the file even GET parameters are used.

After implementation of the feature add a section about configuration to README.md file

**Comment by vbaranov** [comment]
I believe, this local structure will work for user, who created the instance of ICO.
But we can't transfer it to any investor by client-side.
will looking for another solution.

**Comment by igorbarinov** [comment]
Yes, this is how it is planned. If you want to use this feature you have to deploy on your instance. 
One instance = one crowdsale.

**Comment by vbaranov** [comment]
@igorbarinov Ah, ok. And owner of the instance will manually change this config after crowdsale creation. Will implement.
