### ISSUE TITLE
Move state management to Redux/Mobx

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#184]
Roman suggested to look into https://github.com/mobxjs/mobx instead of Redux

**Comment by rstormsf** [comment]
@igorbarinov @vbaranov https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx - great quick intro to mobx

**Comment by 15chrjef** [comment]
I disagree, to my understanding redux is the best state management system I for react. It has newly gained large enterprise usage for its usefulness. Would be happy to do a deep dive on this issue roman.

**Comment by vbaranov** [comment]
@15chrjef current state structure is [here](https://github.com/oraclesorg/ico-wizard/blob/master/ICO_wizard_state_example.json)

**Comment by 15chrjef** [comment]
{
"compilerVersion": "0.4.11",
"contractName": "MintedTokenCappedCrowdsaleExt",
"contractType": "white-list-with-cap",
"contracts": {
"token": {
"src": "",
"bin": "",
"abi": [],
"addr": "",
"abiConstructor": ""
},
"crowdsale": {
"src": "",
"bin": "",
"abi": [],
"addr": [],
"abiConstructor": []
},
"pricingStrategy": {
"src": "",
"bin": "",
"abi": [],
"addr": [],
"abiConstructor": []
},
"multisig": {},
"nullFinalizeAgent": {
"src": "",
"bin": "",
"abi": [],
"addr": "",
"abiConstructor": ""
},
"finalizeAgent": {
"src": "",
"bin": "",
"addr": [],
"abiConstructor": []
},
"tokenTransferProxy": {},
"safeMathLib": {
"src": ""
"bin": ""
"addr": "",
"abiConstructor": ""
}
},
"optimized": true,
"token": {
"name": "MyToken",
"ticker": "MTK",
"supply": 0,
"decimals": "18"
}
"reservedTokens": [{
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"dim": "tokens",
"val": "10"
}],
"reservedTokensElements": [{
"key": "0",
"ref": null,
"props": {
"num": 0,
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"dim": "tokens",
"val": "10"
},
"_owner": null,
"_store": {}
}],
"reservedTokensInput": {
"dim": "tokens",
"addr": "",
"val": ""
},
"stepTwoValidations": {
"tier": "VALIDATED",
"startTime": "VALIDATED",
"endTime": "VALIDATED",
"walletAddress": "EMPTY",
"supply": "VALIDATED",
"rate": "VALIDATED",
"updatable": "INVALID"
},
"stepThreeValidations": {
"tier": "VALIDATED",
"startTime": "VALIDATED",
"endTime": "VALIDATED",
"supply": "VALIDATED",
"rate": "VALIDATED",
"updatable": "INVALID"
},
"pricingStrategy": [{
"rate": "10000"
},
{
"rate": "1000"
}
],
"crowdsale": {
"startTime": "2017-09-28T17:05",
"endTime": "2017-10-03T00:05:00",
"walletAddress": "0x005364854d51a0a12cb3cb9a402ef8b30702a565",
"supply": "1000"
}
"whitelist": {
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"min": "1",
"max": "10"
},
"whiteListElements": {
"key": "0",
"ref": null,
"props": {
"crowdsaleNum": 0,
"whiteListNum": 0,
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"min": "1",
"max": "10"
},
"_owner": null,
"_store": {}
},
"whiteListInput": {
"addr": "",
"min": "",
"max": ""
},
tiers: [
{
"tier": "Tier 1",
"updatable": "on",
"whitelistdisabled": "no"
},
{
"tier": "Tier 2",
"supply": "1000",
"updatable": "on",
"whitelist": [],
"whiteListElements": [],
"whiteListInput": {},
"startTime": "2017-10-03T00:05:00",
"endTime": "2017-10-07T00:05:00"
}
],
}

**Comment by vbaranov** [comment]
My suggestions:
1. 
```
"crowdsale": {
"startTime": "2017-09-28T17:05",
"endTime": "2017-10-03T00:05:00",
"walletAddress": "0x005364854d51a0a12cb3cb9a402ef8b30702a565",
"supply": "1000"
}
```
Only `walletAddress` here is the global parameter of the crowdsale. Others relate to tier. I suggest, to move `startTime`, `endTime`, `supply` back  to `tiers[0]` element properties.
2. 
```
"whitelist": {
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"min": "1",
"max": "10"
},
"whiteListElements": {
"key": "0",
"ref": null,
"props": {
"crowdsaleNum": 0,
"whiteListNum": 0,
"addr": "0x005364854d51A0A12cb3cb9A402ef8b30702a565",
"min": "1",
"max": "10"
},
"_owner": null,
"_store": {}
},
"whiteListInput": {
"addr": "",
"min": "",
"max": ""
},
```
It is the `tier[0]` properties too. It should be moved there.

In this case the total change, that you suggest is to 
1. rename `crowdsale[]` to `tiers[]`
2. move `walletAddress` property from `tiers[0]` to `crowdsale{}`

Right @15chrjef ?

**Comment by 15chrjef** [comment]
Those are the changes yes, but what does 'it' refer to in 'It is the tier[0] properties too. It should be moved there.'? Should the whitelist, whitelistelement, _owner, _store, and whiteListInput all be moved to tier?

**Comment by 15chrjef** [comment]
@vbaranov updated json above.

**Comment by vbaranov** [comment]
>Those are the changes yes, but what does 'it' refer to in 'It is the tier[0] properties too. It should be moved there.'? Should the whitelist, whitelistelement, _owner, _store, and whiteListInput all be moved to tier?

Yes, Jeff. They should be moved to the first element of tiers array (except _owner, _store): each tier has own whitelist, whitelistelement, _store, and whiteListInput.

**Comment by 15chrjef** [comment]
alright, updated JSON above, let me know if there are any other changes to be made otherwise, I'll start working on state management.

**Comment by igorbarinov** [comment]
Implemented here https://github.com/oraclesorg/ico-wizard/pull/363
