### ISSUE TITLE
Add How to verify contracts in Etherscan section to the README.md

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#185]
Also will need to modify data on Step 4 and downloaded text file:
- optimization status
- remove quotes from ABI constructor
- add address of :SafeMathLibExt and name of the library

Add instruction to README.md

**Comment by vbaranov** [comment]
The addresses and source codes of the following contracts should be added too:
- Token
- Pricing strategy
- FinalizeAgent
