### ISSUE TITLE
File Configuration of Components

### ISSUE THREAD

**Issue by 15chrjef** [oraclesorg/ico-wizard#190]
Each Component Should have its own directory in the components directory and should have their own constants, utils, and eventually, actions and reducers files.

The current file such as stepOne.js should be replaced with index.js as follows in the directory.

```
components 
  stepOne
     utils.js
     constants.js
     index.js
     reducers.js
     actions.js
```

**Comment by vbaranov** [comment]
@15chrjef could we close it?

**Comment by 15chrjef** [comment]
Yes. Should be fine for now.
