### ISSUE TITLE
Validation isn't correct for multiple tiers in step 3

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/ico-wizard#233]

**Comment by igorbarinov** [comment]
@vbaranov is it fixed?

**Comment by vbaranov** [comment]
Waiting of https://github.com/oraclesorg/ico-wizard/issues/184 implementation

**Comment by fvictorio** [comment]
Is this still valid?

**Comment by vbaranov** [comment]
These problems still exist:
1. no validation for end time > start time for 2nd tier and further
2. no validation, that start time of the tier cannot be less than end time of the previous tier
