### ISSUE TITLE
Sweetalert before 3 and 4 step for awareness about number of tranasctions AND running only one instance of Wizard

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#235]
Before starting to sign transactions show a sweetalert with number of TXs

"You are about to sign n TXs. You will see an individual Metamask windows for each of it. Please don't open two or more instances of Wizard in one browser."

**Comment by igorbarinov** [comment]
Inspired by https://github.com/oraclesorg/ico-wizard/pull/226#issuecomment-334782755

**Comment by vbaranov** [comment]
![screen shot 2017-10-11 at 18 21 20](https://user-images.githubusercontent.com/4341812/31450034-1247c6f0-aeb1-11e7-96a5-6bde2c8e0b8b.png)
