### ISSUE TITLE
Error: Cannot find module 'C:\Users\v...\ico-wizard\$npm_package_config_combine_solidity_script'

### ISSUE THREAD

**Issue by wrisx** [oraclesorg/ico-wizard#236]
Script missing so npm start fails with this error without executing... Any thoughts where to find it?

**Comment by vbaranov** [comment]
Did you follow these steps for running https://github.com/oraclesorg/ico-wizard#run-local-version-for-development ?

**Comment by wrisx** [comment]
I did, but not sure correctly. What changes need to be made to the command to run it on windows? Also, the demo config parameters need to be changed or can that address be used that's there?

**Comment by vbaranov** [comment]
I've updated [Run local version for development](https://github.com/oraclesorg/ico-wizard#run-local-version-for-development) section for Windows users.
Please, check it. Thank you for report!
As about [config](https://github.com/oraclesorg/ico-wizard#ico-configuration), it is empty, by default. When you'll create your crowdsale on your instance, you can set the address of your crowdsale contract there.
