### ISSUE TITLE
Wizard hangs on Mainnet after 2nd tx with Basic scenario

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#237]
When deploying to mainnet, the Wizard doesn't handle exception
"main.3ba23847.js:1 Unhandled rejection Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined!"

I reproduced it and time between submitting tx and this error is much less than 50 blocks time, which is like 50*15sec=12.5 minutes

**Comment by rstormsf** [comment]
it might be a problem with web3 1.0....maybe old (metamask) version could help?

**Comment by igorbarinov** [comment]
@rstormsf We have another bug on old one)

**Comment by rstormsf** [comment]
@igorbarinov infura might help

**Comment by rstormsf** [comment]
@rstormsf if client side web3 fails, fallback to infura

**Comment by vbaranov** [comment]
Fixed for mainnet with customized web3. Emergency alert is disabled for both links: master and stage
