### ISSUE TITLE
Refactor style of code

### ISSUE THREAD

**Issue by 15chrjef** [oraclesorg/ico-wizard#25]
-replace '$this' with 'this' across the application. Using jquery like syntax is an anti-pattern in react

-use ES6 instead of regular javascript/ES5 or lower
   -replace 'var' with the usage of let of const. 
   - use arrow functions () => rather than function() {} in most cases

-extract most of the logic into separate class or util functions, 
   -right now there is too much logic in componentDidMount/componentWillMount, each function should have all of its logic at the same level of abstraction and be very readable by anyone who is not familiar with JS or react

- state should be extracted at the application level, or passed down through props, not passed down as state to be mutated continually i.e. going passing and using state from home -> page1

- remove nested ternary operators, multiple functions should be used to extract this logic or use &&/|| operators

- don't mutate state directly any state changes should be made with this.setState({}) using the this.state = 'hello' will cause re-render issues within react

-remove console logs 

-add extensive variable naming, i.e. using descriptive words to describe the items one is iterating over instead of 'i' in a for loop

**Comment by igorbarinov** [comment]
@15chrjef @vbaranov can we consider it to accepted and may close it?

**Comment by vbaranov** [comment]
Refactoring is not finished yet

**Comment by 15chrjef** [comment]
Agreed, thank you for getting to this before I @vbaranov
