### ISSUE TITLE
New format of downloaded file with metadata on Step 4

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#269]
Problem A:
At the moment, all files with contracts and metadata have the same name for all networks. When a user creates a crowdsale we download "contractinfo.txt" file on the host.
It results of having files like `contractinfo (10).txt`

Proposal:
- change file to zip file with sol and metadata files inside

`icowizard_%network name or id for unknown network%token.zip`

e.g.
```
icowizard_kovan_0x2c57E1E3AD53F0b971422696c1470cEB84F83B1B.zip
icowizard_mainnet_0xca9B0753E2Ea13d7bBE0e90516Bcf940A275eFA8.zip
```

Problem B:
- it's hard to copy and paste from txt file
- it's hard to auditors to understand file structure

Solution:

Each file will have all created contracts named by contract name with _ and number as a number of tier
e.g. 
```
SafeMathLibExt.sol
MintedTokenCappedCrowdsaleExt_1.sol
MintedTokenCappedCrowdsaleExt_2.sol
CrowdsaleTokenExt.sol
FlatPricingExt_1.sol
FlatPricingExt_2.sol
NullFinalizeAgentExt.sol
ReservedTokensFinalizeAgent.sol
```

and metadata (ABI, Constructor, etc.)
```
SafeMathLibExt.txt
MintedTokenCappedCrowdsaleExt_1.txt
MintedTokenCappedCrowdsaleExt_2.txt
CrowdsaleTokenExt.txt
FlatPricingExt_1.txt
FlatPricingExt_2.txt
NullFinalizeAgentExt.txt
ReservedTokensFinalizeAgent.txt
```

**Comment by fvictorio** [comment]
Two questions about the zip part:

1. The address of the contract should be included in their txt file, right?
2. What should we do with the general information that is at the beginning of the file? (Compiler version, optimization, etc.) Maybe another txt file? Something like `GeneralInformation.txt`.

**Comment by igorbarinov** [comment]
> The address of the contract should be included in their txt file, right?
good idea

> What should we do with the general information that is at the beginning of the file? (Compiler version, optimization, etc.) Maybe another txt file? Something like GeneralInformation.txt.

I suppose it will be included in each txt file corresponding to .sol file. Any suggestions?

**Comment by vbaranov** [comment]
>I suppose it will be included in each txt file corresponding to .sol file. Any suggestions?
Though, for example, `Compiler version` is common for all contracts, I support to put it to all txt files to have all data for verification of one contract in one txt file + source code in .sol.

**Comment by igorbarinov** [comment]
each txt file will have it's own 
- abi
- encoded parameters
- contract address

thus, we will have 3 types of files
I suggest to have two types of files
- solidity code
- metadata

**Comment by vbaranov** [comment]
Yes, good idea to store an order in the name of the file.

**Comment by fernandomg** [comment]
As a final review, this is how it will be solved.

**1 Tier**
- prefix unique per file
- no suffixes

```
001_SafeMathLibExt.sol
002_SafeMathLibExt.txt
003_CrowdsaleTokenExt.sol
004_CrowdsaleTokenExt.txt
005_MintedTokenCappedCrowdsaleExt.sol
006_MintedTokenCappedCrowdsaleExt.txt
007_FlatPricingExt.sol
008_FlatPricingExt.txt
009_NullFinalizeAgentExt.sol
010_NullFinalizeAgentExt.txt
011_ReservedTokensFinalizeAgent.sol
012_ReservedTokensFinalizeAgent.txt
```

**2 Tiers (and more)**
- prefix unique per file
- suffix only when needed
-  `.sol` files for the same contract will have the same content, i.e.: `003_CrowdsaleTokenExt_1.sol` and `005_CrowdsaleTokenExt_2.sol` will be indentical.
- `.txt` files for the same contract will differ in the `contract address for Tier` and `contract ABI encoded constructor arguments` only, the rest of the files will be the same.

```
001_SafeMathLibExt.sol
002_SafeMathLibExt.txt
003_CrowdsaleTokenExt_1.sol
004_CrowdsaleTokenExt_1.txt
005_CrowdsaleTokenExt_2.sol
006_CrowdsaleTokenExt_2.txt
007_MintedTokenCappedCrowdsaleExt.sol
008_MintedTokenCappedCrowdsaleExt.txt
009_FlatPricingExt_1.sol
010_FlatPricingExt_1.txt
011_FlatPricingExt_2.sol
012_FlatPricingExt_2.txt
013_NullFinalizeAgentExt.sol
014_NullFinalizeAgentExt.txt
015_ReservedTokensFinalizeAgent_1.sol
016_ReservedTokensFinalizeAgent_1.txt
017_ReservedTokensFinalizeAgent_2.sol
018_ReservedTokensFinalizeAgent_2.txt
```

**Comment by igorbarinov** [comment]
Looks good. @vbaranov what do you think?

**Comment by igorbarinov** [comment]
We need to add this format of downloaded file to Wiki after implementation

**Comment by vbaranov** [comment]
Yes, agree. Wait for PR.
