### ISSUE TITLE
Show toast notification when a file with contracts is downloaded

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#270]
Problem:
We need to download the file to user's computer because he may forget to do this. Now we do it without asking user's permission and not notifying him. It may be considered as unfriendly action by a user.

Solution:
Present a toast notification in the right top corner with a text "A file with contracts and metadata downloaded on your computer"

**Comment by fernandomg** [comment]
@igorbarinov #271 seems to replace what's proposed here, as it's discarding the option of auto-download.
