### ISSUE TITLE
Add validation on Invest button

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#273]
Problem: It is possible to press invest with an empty token field and get success message

![image](https://user-images.githubusercontent.com/424628/31592697-fbb7d4c6-b1de-11e7-9f37-70b944c78b7c.png)

If invest amount is undefined  show a validation message under the invest page "Number of tokens to buy should be positive "

**Comment by fernandomg** [comment]
@igorbarinov Can you assign me this issue?

The solution will make the message appear under the input if the user enters an invalid token or tries to submit it. Is it ok this way?

**Pristine**
![pristine-form](https://user-images.githubusercontent.com/3315606/32288721-9698d634-bf13-11e7-82e8-78b8d7a16367.png)

**Invalid**
![invalid-token](https://user-images.githubusercontent.com/3315606/32288733-9e590c68-bf13-11e7-844b-a74ca3781521.png)

**Valid**
![valid-token](https://user-images.githubusercontent.com/3315606/32288783-c32f77ac-bf13-11e7-9be6-735d418b46c7.png)

**Comment by igorbarinov** [comment]
@fernandomg I've added you and Franco as collaborators to the project, please accept and assign this issue. Proposed validation is ok to me.
