### ISSUE TITLE
 too many decimal places error 

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#274]
Error in Chrome:
```
Uncaught Error: [ethjs-unit] while converting number 0.0008333333333333334 to wei, too many decimal places
    at Object.a [as toWei] (main.db12aa03.js:1)
    at Object.d [as toWei] (main.db12aa03.js:1)
    at m (main.db12aa03.js:1)
    at r (main.db12aa03.js:1)
    at main.db12aa03.js:1
    at i (main.db12aa03.js:1)
    at main.db12aa03.js:1
```

Parameters to retest

> I have enabled "Allow to modify" for both tiers. No Whitelists, Tier1Supply: 30000000, Tier2Supply: 170000000. Tier1Rate: 1600, Tier2Rate: 1200. StartTime/EndTime Default. The rest is Default too.
>TIer1Minimum Investor cap: 6400 tokens
>Name: Blockport, Ticker: BPT, Decimals: 18
>So in total the Supply will be: 200000000
>Tested without enabling "Allow to modify" --> still not working

**Comment by igorbarinov** [comment]
Ok. It fixed the problem for the user
@vbaranov Please add PR on the `master` branch following PR rules. Thank you

**Comment by allenhark** [comment]
Great!

**Comment by renaldas** [comment]
seems it's fixed on git, but not on the live site?

**Comment by igorbarinov** [comment]
@renaldas it's deployed on https://wizard-stage.oracles.org
not deployed on wizard.oracles.org because PR is still in review https://github.com/oraclesorg/ico-wizard/pull/281
