### ISSUE TITLE
submodules\oracles-combine-solidity

### ISSUE THREAD

**Issue by rfikki** [oraclesorg/ico-wizard#282]
Could not install from "submodules\oracles-combine-solidity" as it does not contain a package.json file.

This is on windows OS.

Complete error:
c:\wamp\www\ico-wizard-master>npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code ENOLOCAL
npm ERR! Could not install from "submodules\oracles-combine-solidity" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rocky\AppData\Roaming\npm-cache\_logs\2017-10-19T15_57_26_903Z-debug.log

**Comment by vbaranov** [comment]
Did you follow these steps: https://github.com/oraclesorg/ico-wizard#run-local-version-for-development ?

**Comment by rfikki** [comment]
Yes, I did:

c:\wamp\www\ico-wizard-master>npm install --global --production windows-build-tools

> windows-build-tools@1.3.2 postinstall C:\Users\Rocky\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.13.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.13.msi. Saved to C:\Users\Rocky\.windows-build-tools\python-2.7.13.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... |Successfully installed Visual Studio Build Tools.
Successfully installed Python 2.7
+ windows-build-tools@1.3.2
added 126 packages in 42.749s

c:\wamp\www\ico-wizard-master>npm install --global node-gyp
C:\Users\Rocky\AppData\Roaming\npm\node-gyp -> C:\Users\Rocky\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.6.2
added 3 packages, removed 4 packages and updated 26 packages in 3.678s

c:\wamp\www\ico-wizard-master>npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code ENOLOCAL
npm ERR! Could not install from "submodules\oracles-combine-solidity" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rocky\AppData\Roaming\npm-cache\_logs\2017-10-19T16_04_07_366Z-debug.log

c:\wamp\www\ico-wizard-master>

**Comment by vbaranov** [comment]
I don't see `git submodule update --init --recursive --remote` this step before `npm install` in your log.

**Comment by vbaranov** [comment]
Some questions:
1. Which Windows version do you use?
2. Git version? git --version
3. do you have .gitmodules file in the root folder of project? What is the content of the file?

**Comment by igorbarinov** [comment]
@rfikki @vbaranov can we close the issue?

**Comment by vbaranov** [comment]
Non reproducible. No response from user for a long time
