### ISSUE TITLE
ICO Wizard got stuck at step 4

### ISSUE THREAD

**Issue by felixulmerzhuo** [oraclesorg/ico-wizard#290]
[wizard.oracles.org-1508616876483.log](https://github.com/oraclesorg/ico-wizard/files/1404428/wizard.oracles.org-1508616876483.log)
![first issue](https://user-images.githubusercontent.com/32988970/31855621-179ba0f8-b6af-11e7-9a7d-839f37ae0518.png)
![fourth issue](https://user-images.githubusercontent.com/32988970/31855622-17b69d04-b6af-11e7-9588-5cba53202b5f.png)
![is this an issue](https://user-images.githubusercontent.com/32988970/31855623-17ceed96-b6af-11e7-96ab-953ab751daad.png)
![second issue](https://user-images.githubusercontent.com/32988970/31855624-17eccfdc-b6af-11e7-984d-09e9f495b50c.png)
![third issue](https://user-images.githubusercontent.com/32988970/31855625-1806812a-b6af-11e7-9b77-d8820a3ff93c.png)

Specs of the contract:
- NAME: DCX
- The name of your token: XDM
- DECIMALS: 8

- RESERVED TOKENS ADDRESS
0x59... percentage	2.5
0x09... percentage	2.5
0x43... percentage	10
0xcE... percentage	10
0x3C... percentage	10
0x0c... percentage	10
0xe2... percentage	2.5
0x95... percentage	2.5

Crowdsale setup name: Stage 1
RATE: 25000
SUPPLY: 20000000
MODIFYING: off
WHITELISTING: disabled
MIN CAP: 250

Crowdsale setup name: Stage 2
RATE: 12500
SUPPLY: 20000000
MODIFYING: off

Crowdsale setup name: Stage 3
RATE: 8333
SUPPLY: 40000000
MODIFYING: off

Crowdsale setup name: Stage 4
RATE: 5000
SUPPLY: 320000000
MODIFYING: off

**Comment by igorbarinov** [comment]
@vbaranov it worked well without float numbers in reserved tokens (2 and 3, instead of 2.5 and 2.5)

**Comment by vbaranov** [comment]
The solution to allow decimals in percents for reserved tokens is online here: https://wizard-stage.oracles.org/
https://github.com/oraclesorg/ico-wizard/pull/296 to merge it with master is under review.
