### ISSUE TITLE
Bridged crowdsale should create "bridge" events for reserved tokens

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#291]
@vbaranov I'm not sure if bridged crowdsale creates "bridge" events for reserved tokens which are created after finalize. If not, we need to add this functionality for reserved tokens.

**Comment by vbaranov** [comment]
Implemented https://github.com/oraclesorg/ico/commit/dba526cd7ef1d74d06aa4fdf67262b9d00b88258
