### ISSUE TITLE
Remove 0x from encoded ABI in downloaded file

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#302]
It prevents smart contracts from being verified with error `
Error! Invalid constructor arguments provided. Please verify that they are in ABI-encoded format`
![image](https://user-images.githubusercontent.com/424628/31957795-be81114a-b8a4-11e7-8d08-98841292f736.png)

**Comment by vbaranov** [comment]
Fix is online at https://wizard-stage.oracles.org and in review for master: https://github.com/oraclesorg/ico-wizard/pull/296.
