### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by youtweakit** [oraclesorg/ico-wizard#307]
100 | });
  101 | setFlatFileContentToState("./contracts/" + contractName + "PricingStrategy_flat.abi", function(_abi) {
  102 |   derivativesIterator++;
> 103 |   state.contracts.pricingStrategy.abi = JSON.parse(_abi);
  104 | 
  105 |   if (derivativesIterator === derivativesLength) {
  106 |     cb(state);
XMLHttpRequest.rawFile.onreadystatechange
src/utils/utils.js:189
186 |         if(rawFile.status === 200 || rawFile.status === 0)
  187 |         {
  188 |             var allText = rawFile.responseText;
> 189 |             cb(allText);
  190 |         }
  191 |     }
  192 | };
Any ideas? deployed on test vds. get this after pressing "continue" button after tx singning.

**Comment by vbaranov** [comment]
Is the source code from master branch? Pull last changes and try again, please.

**Comment by youtweakit** [comment]
Ok i'll try.

**Comment by youtweakit** [comment]
It's all right now.
