### ISSUE TITLE
(Bug) Possible overflow with high rate of tokens

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#313]
Contract deployed on the Mainnet
https://wizard.oracles.org/invest?addr=0xA2bfa5A11336aB74b642dFDD594502B48783816e&networkID=1

Rate is 282500000 tokens for 1 ETH
Supply is also 282500000

While buying one token the price is set 3.359 ETH 
and should be 1/282500000 ETH

**Comment by igorbarinov** [comment]
![image](https://user-images.githubusercontent.com/424628/32202652-699b1954-bd9b-11e7-9577-65a11ba43cb0.png)

**Comment by vbaranov** [comment]
Fix is online at https://wizard-stage.oracles.org and in review for master: #296.
