### ISSUE TITLE
(Feature) Add investment option without Metamask

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#319]
**Rationale**
There are customers of ICO who don't have Metamask of other Web3-injected wallet installed. In this issue, we add an option of buying tokens without using web3 injected wallet

**Implementation**
A list box with investment methods is added. It has two options Metamask and QR. Metamask is the default option if Metamask is present.
![image](https://user-images.githubusercontent.com/424628/32287316-a2711b40-beed-11e7-8d5b-5101954ebe71.png)

If the Metamask option is selected then on Invest button web3 event triggered.
If QR is selected then this set of controls and views is presented
![image](https://user-images.githubusercontent.com/424628/32287324-adbf71cc-beed-11e7-9152-e8e674f5d9dd.png)
- qr code. some research needs to be done:
   - [ ] check if QR code can have method id (data) embedded
   - [ ] check if QR code can have wallet and amount embedded
- label with the worth of selected tokens in ETH
- address
- control to copy the address. The toast should appear after successful copying
- progress bar. The page will poss crowdsale address for a number of tokens specified to invest on crowdsale contract. Should be a polling with 2(?) seconds
- memo to use data (protection from sending from exchanges)

After poll will catch the event the view will be changed to 
![image](https://user-images.githubusercontent.com/424628/32287582-88e093c6-beee-11e7-8ffb-19f5ebed4207.png)

It's possible that polling will get someone else investment for the same amount. We can add an additional parameter to buy() which will be emitted into the blockchain log. @vbaranov what do you think?

**Comment by fvictorio** [comment]
I think is better to start with a QR code just with the address. Encoding more information in a URI (that then can be converted to a QR) seems to be an open proposal: https://github.com/ethereum/EIPs/issues/67.

**Comment by igorbarinov** [comment]
I agree, let's start with the address
