### ISSUE TITLE
(Bug) Investment Transaction rejection not being handled properly

### ISSUE THREAD

**Issue by fernandomg** [oraclesorg/ico-wizard#320]
If the user rejects invest transaction, app will display the popup with with the message _Congrats! You've successfully bought *n* tokens!_.

Popup should not appear or message should be different.

**Screenshot**
![unhandled-rejection](https://user-images.githubusercontent.com/3315606/32289406-688d0556-bf15-11e7-8989-9a13e3fb2441.png)

**Comment by igorbarinov** [comment]
The popup should not appear on reject. What's about toast notification?

**Comment by fernandomg** [comment]
I like the idea of a toaster. Have any on mind?

I've found these:
1. https://github.com/schiehll/react-alert (I find it quite suitable for the solution)
2. https://github.com/tomchentw/react-toastr
3. https://github.com/jesusoterogomez/react-notify-toast
4. https://github.com/igorprado/react-notification-system

**Comment by igorbarinov** [comment]
I like the first one. Our designer approved it.
We can use the toast to inform which contract we create between step 3 and 4. @vbaranov what do you think.
