### ISSUE TITLE
Reserve tokens for early contributors (Project 001)

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#34]
Additional block in Step 2. An organizer can add a string with a pair of address and amounts of tokens reserved. There is a + button to add next row.

CAP = CAP - SUM(RESERVED AMOUNTS)
Regular crowd buyers can't buy reserved amount. After crowdsale ends, reserved buyers can't buy reserved amounts and it will be burned.

**Comment by 4ntoine** [comment]
It would be great to have possibility to import initial balances from some contract (let's say pre-ICO smart contract). Any other possibility to stage pre-ICO and ICO linked?

**Comment by igorbarinov** [comment]
Will be added to Token configurations with
- fixed amount 
- flexible (%) after crowdsale

**Comment by igorbarinov** [comment]
Implemented in Step2 (TokenSetup)
