### ISSUE TITLE
Createing crowdsale tokens problem 

### ISSUE THREAD

**Issue by mostafa1970** [oraclesorg/ico-wizard#371]
While creating crowdsale tokens using wizard.  I reach phase 4 , It was suspended without responding ..any help ..Pls.

**Comment by vbaranov** [comment]
At which network do you have this problem?
Do you have any errors in chrome developer console?

**Comment by igorbarinov** [comment]
@mostafa1970 please provide screenshots and logs from developer console

**Comment by mostafa1970** [comment]
Dear igor

here is the token setting info file ... please create that token for me and
send me the download file from step 4 and the url of  crowdsale page after
published .. reagrds  — moustafa mahgmoud




بتاريخ ٢٤‏/١١‏/٢٠١٧ ٨:٤١ م، كتب "Igor Barinov" <notifications@github.com>:

@mostafa1970 <https://github.com/mostafa1970> please provide screenshots
and logs from developer console

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/oraclesorg/ico-wizard/issues/371#issuecomment-346881644>,
or mute the thread

**Comment by mostafa1970** [comment]
here's the screenshot for where i stopped

**Comment by mostafa1970** [comment]
*Yes i did a "tier" structure .. but it is still suspended at phase 4 .*
*look at the attachment *

**Comment by igorbarinov** [comment]
@mostafa1970 when you add attachments by email it's not attached. Please attach
- screenshots
- chrome developer console screenshot/logs
- parameters of your crowdsale
- the network you are using
