### ISSUE TITLE
Continued issues trying to create a crowdsale token - multiple questions

### ISSUE THREAD

**Issue by GreenCampusAdmin** [oraclesorg/ico-wizard#373]
Will I be able to go onto the next step if I do not have 0.32 ETH?

<img width="1680" alt="screen shot 2017-11-24 at 18 38 29" src="https://user-images.githubusercontent.com/32910951/33222216-80dcf694-d14d-11e7-8fbf-3966dd73411a.png">

<img width="1680" alt="screen shot 2017-11-24 at 19 12 11" src="https://user-images.githubusercontent.com/32910951/33222219-89099d0e-d14d-11e7-8826-fc453f35a284.png">

I'm too poor for this even. I have loads of investors wanting to invest in Green Camp but I cant afford to set up any investment vehicles! 

Thanks

Charles

**Comment by GreenCampusAdmin** [comment]
Also, may I ask, if I do create these tokens, how can people buy them? Thanks

**Comment by GreenCampusAdmin** [comment]
I have made it to the next screen but when I try to publish it tells me:

<img width="1680" alt="screen shot 2017-11-24 at 19 39 34" src="https://user-images.githubusercontent.com/32910951/33222454-5ca9419a-d14f-11e7-8779-24d02ae24878.png">

<img width="1680" alt="screen shot 2017-11-24 at 19 39 56" src="https://user-images.githubusercontent.com/32910951/33222457-6249de34-d14f-11e7-8568-2947acea2010.png">
<img width="1680" alt="screen shot 2017-11-24 at 19 39 41" src="https://user-images.githubusercontent.com/32910951/33222458-625c5ac8-d14f-11e7-8781-627ae63ec31d.png">

Please advise

**Comment by vbaranov** [comment]
>Please, read instruction before you'll start to create crowdsales using ICO Wizard. Consider to deploy on the Mainnet after testing on Kovan testnet.

Please, carefully read README, especially deploying to mainnet section: https://github.com/oraclesorg/ico-wizard#deploying-of-crowdsale-to-mainnet
You need to sign all transactions before you will get your crowdsale page.
