### ISSUE TITLE
Problem create new project

### ISSUE THREAD

**Issue by alexgazin** [oraclesorg/ico-wizard#374]
Hello! Everytime I'm trying co create Crowdsale contract I get this message on step 4
![image_2017-11-26_16-30-41](https://user-images.githubusercontent.com/18518183/33240744-23c4c7c2-d2cc-11e7-8c86-fa096aa41f7a.png)
but it's not empty, I even downloaded it
[icowizard_Mainnet_0x3c983bfD04C270dC33484c000bacE5Ad11c74A41.zip](https://github.com/oraclesorg/ico-wizard/files/1503955/icowizard_Mainnet_0x3c983bfD04C270dC33484c000bacE5Ad11c74A41.zip)
also I created 4 empty smart-contracts
https://etherscan.io/tx/0xcc38cef10c0931cedb2e222a6f47a58cb06d1ed6b2144ea459b20441184931b3
https://etherscan.io/tx/0xfcb629633cbd6571fb5430681eebc6806d51e53b9279ccc9f558ab9983466b12
https://etherscan.io/tx/0x17be17d801c470e32d3af18d0e3522265cc4fad99dcdfc17ad72f475321c0184
https://etherscan.io/tx/0x60ee1fddc9f5278316a7112185a1ac61c532a55cae8869553a5d27d7ad303cb6

**Comment by igorbarinov** [comment]
Could you open View-> Developer -> Developer Tools and post a screenshot from Console if there are any red messages.
Also, a log of your console will be beneficial.

**Comment by igorbarinov** [comment]
@alexgazin any chance to get log from Chrome?

**Comment by alexgazin** [comment]
I see this error in the console. Do I need more information for diagnosis?
![image_2017-11-26_22-21-02](https://user-images.githubusercontent.com/18518183/33253481-b5e6e58a-d354-11e7-987e-4ea2064c631a.png)

**Comment by igorbarinov** [comment]
It said that you rejected tx. Can you reproduce your steps?

**Comment by alexgazin** [comment]
Of course, it will take a while to wait...

**Comment by igorbarinov** [comment]
Like how long?

Can you scroll up and check for other errors?

**Comment by igorbarinov** [comment]
Please record a video of your process using Monosnap https://monosnap.com/welcome
or OBS https://obsproject.com/
here is an example of me recording Wizard with OBS https://www.youtube.com/watch?v=p6KgSk41TDM
you can arrange windows in different layers. Nice software

**Comment by alexgazin** [comment]
Thanks, I'll try. Sorry for the long communication. Sorry me for being rude and impudent, but do you need a Java developer for the team? p.s for backend

**Comment by igorbarinov** [comment]
@alexgazin any progress on your video. We'd like to close the issue.
