### ISSUE TITLE
cant verify contract on etherscan

### ISSUE THREAD

**Issue by dcxblockchain** [oraclesorg/ico-wizard#377]
Hi

Im trying to verify the contracts i made with the wizard but get an error 

Sorry! The Compiled Contract ByteCode for 'MintedTokenCappedCrowdsaleExt' does NOT match the Contract Creation Code for Address 0xDeda0fe6fC7A64c3a200C5612b2E99dF0E6Ee453.

 Error! Library Name(s) and Address(es) was required but not provided.

Unable to Verify Contract Source Code.

what do i need to fill in for library and adress?

**Comment by igorbarinov** [comment]
Please use the instruction how to verify a contract https://github.com/oraclesorg/ico-wizard/wiki/ICO-Wizard-Verifying-Contracts

**Comment by dcxblockchain** [comment]
Thnx i allready figured it out.
