### ISSUE TITLE
Refunding ico users and contract bug

### ISSUE THREAD

**Issue by supadupa2** [oraclesorg/ico-wizard#379]
Hi, my contract start date is in afew days and at the https://wizard.oracles.org/invest?addr= the crowdsale contract address is blank, is this normal?

How do i refund a token holder if he fails to do KYC?

**Comment by fvictorio** [comment]
Do you have the address of the crowdsale? If you bookmarked the page after deploying the contracts, or if you downloaded the ZIP file with the details of the deployed contracts, you should be able to recover it.

**Comment by igorbarinov** [comment]
> How do i refund a token holder if he fails to do KYC?

You can do whitelist tier and put user to whitelist _after_ KYC
