### ISSUE TITLE
Replace block start and block end on Crowdsale setup to Date/Time

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/ico-wizard#38]
Replace block start and block end on Crowdsale setup to Date/Time. It will be more convenient for users to specify time instead of block. Start time can't be set up before current date and time.

Need to change on Crowdsale and Publish pages

**Comment by vbaranov** [comment]
It is replaced. 

> Start time can't be set up before current date and time.

moved to [Form validation issue](https://github.com/oraclesorg/ico-wizard/issues/42)
