### ISSUE TITLE
transactions to contract fail

### ISSUE THREAD

**Issue by dcxblockchain** [oraclesorg/ico-wizard#380]
Hi, 

i wanted to test the crowdsale but all transactions i do end up faling see for example

https://etherscan.io/tx/0x0b7323cbab91a8074b19f54f2ea17a9e47d6159154f852105073fec848e6a940

any idea why this is?

**Comment by dcxblockchain** [comment]
see also

https://etherscan.io/tx/0x314ef091a026d052a11856249864416ba30499dca7dd05d69bd46fb85be8fbcd

**Comment by igorbarinov** [comment]
I see it here https://wizard.oracles.org/invest?addr=0xDeda0fe6fC7A64c3a200C5612b2E99dF0E6Ee453&networkID=1

@dcxblockchain 
- do you have whitelist enabled?
- if not, what is min amount to contribute?

**Comment by vbaranov** [comment]
There is no whitelist, as I see from here: https://etherscan.io/address/0xDeda0fe6fC7A64c3a200C5612b2E99dF0E6Ee453#readContract
And there is min cap = 7.5 tokens, as I see from here: https://etherscan.io/address/0xbe8eb4c36a6f6ccb9bdb8533be70dc5988011466#readContract
@dcxblockchain success buying starts with the value of tokens > 7.5. I'll close the issue.
