### ISSUE TITLE
Error submitting transactions to kovan network from ICO Wizard

### ISSUE THREAD

**Issue by hashguide** [oraclesorg/ico-wizard#383]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Kovan Test Network

### If you were able to create it, what is the URL of your crowdsale?

First transaction was successful, second says it failed on Metamask, but on Kovan.etherscan it shows successful, third transaction failed on metamask and doesn't even show up on Kovan.etherscan.
https://kovan.etherscan.io/address/0xfa229b4e01d2f184d7fd6b41352354c5be402791

### Do you have screenshots showing the problem?

Yes, showing the two failures and I left the ethereum address from etherscan above.

### Do you see errors in the dev console? If yes, please include a screenshot

Dev console shows no errors, just some non associated warnings.

---

![metamask-error](https://user-images.githubusercontent.com/31787330/33518222-77117974-d75f-11e7-8ad7-ac8c895adc63.png)
![metamask-error2](https://user-images.githubusercontent.com/31787330/33518223-771ed7a4-d75f-11e7-9d64-7b749dadf318.png)

**Comment by fvictorio** [comment]
Hi, I think this is an issue with MetaMask. It often happens to me during development.

Can you try disabling and enabling the MetaMask extension (right click in the MetaMask icon, Manage extensions)?

**Comment by igorbarinov** [comment]
@fvictorio 
- Stephen had this problem multiple times
- For him, the problem is more Kovan specific. Maybe because there is no Byzantinum there? Or because he tested there more often :-)
- Our DApp should resubmit transaction with a new nonce when submitted tx was rejected. Don't you think so?

**Comment by fvictorio** [comment]
Sure, I'll do some research around this.

@hashguide Does this happen randomly or do you know of some sequence of steps that will always trigger the problem?

**Comment by fvictorio** [comment]
I'm having a hard time trying to reproduce this. Plus, it seems like Kovan is having issues (some transactions take forever, etherscan behaves weirdly, there are people complaining in the gitter channel). So I'll wait until the network is working well again to try again, but it'd be helpful to have some pointers related to how to reproduce the issue.

**Comment by hashguide** [comment]
Sorry didn't see these, I will try to reproduce it after cycling metamask.

**Comment by fvictorio** [comment]
Awesome, thanks.

**Comment by hashguide** [comment]
While submitting on the Kovan network, everything seems to work fine now.
