### ISSUE TITLE
(Fix) Change gas price to 10 GWei 

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/ico-wizard#390]
https://ethgasstation.info/
![screen shot 2017-12-05 at 11 45 51](https://user-images.githubusercontent.com/4341812/33627371-2a87c36a-d9b2-11e7-84a8-942070af3442.png)

**Comment by igorbarinov** [comment]
Wait

**Comment by igorbarinov** [comment]
Let's add a list box from here? https://github.com/oraclesorg/ico-wizard/issues/283

**Comment by fvictorio** [comment]
I assigned that issue to myself but didn't start it. I can do it now.

Question: In which step should we add the gas price options? Step 2 or 3?

**Comment by igorbarinov** [comment]
For me both Step 2 and 3 are ok. I think Step 3 is better if we will dynamically get the price because it's closer to deployment.

**Comment by igorbarinov** [comment]
Hm, with current price
Normal will be 10, slow 5 and fast 15
https://ethgasstation.info/

**Comment by youtweakit** [comment]
I think that timeout for the new transaction generation must be bit higher.  It's set up in TokenMarket's ICO code. Got This on mainnet - [https://youtu.be/9NExDWYjeFQ](url)

**Comment by igorbarinov** [comment]
@youtweakit please create an issue

**Comment by vbaranov** [comment]
Could be closed due to https://github.com/oraclesorg/ico-wizard/issues/283
