### ISSUE TITLE
issue in sending tokens

### ISSUE THREAD

**Issue by supadupa2** [oraclesorg/ico-wizard#394]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0xACf1351BF74EA3e668cCD9a451884BcEF1296dAc&networkID=1

### Do you have screenshots showing the problem?

No
### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

we have a contributor who sent ether without the command can he reverse it somehow?

Is it possible to refund any contributor and cancel the tokens before finalize?

---

**Comment by supadupa2** [comment]
the gas issue seems to be manageable the gas just fails. Would appreciate if it was possible to know how to revoke a contribution's tokens and refund a user?

**Comment by igorbarinov** [comment]
We don't have refund feature
After crowdsale end and finalize the crowdsale:
- ask your user to return tokens to your account
- send him ether from your wallet
