### ISSUE TITLE
Global min cap does not seem to be working

### ISSUE THREAD

**Issue by fvictorio** [oraclesorg/ico-wizard#395]
I created a crowdsale with 5 as "Investor Min Cap" but then was able to buy 3 tokens.

@vbaranov @igorbarinov can you confirm this?

**Comment by igorbarinov** [comment]
I confirm. Global min limit doesn't work on one-tier crowdsale
tested here https://kovan.etherscan.io/address/0x4e842078741583ea5c4c7014088bf443dc27d3bf#internaltx
[icowizard_Kovan_0xB97AE459f8aBBE00a346eA7ab762bBc4cE649CE5.zip](https://github.com/oraclesorg/ico-wizard/files/1548307/icowizard_Kovan_0xB97AE459f8aBBE00a346eA7ab762bBc4cE649CE5.zip)
