### ISSUE TITLE
how to extend crowdsale stage

### ISSUE THREAD

**Issue by dcxblockchain** [oraclesorg/ico-wizard#400]
Hi, 

I want to change endsAt value to extend presale period. But if i execute endsAt and fill in the new timestamp it does get  processed but value is not changing. 

Br
Martijn

**Comment by igorbarinov** [comment]
Hi,
if your tier is updatable then use instruction by @hashguide in our Wiki
https://github.com/oraclesorg/ico-wizard/wiki/Set-Crowdsale-Start-and-End-Time

If your tier was created as non-updatable then no way. Create another crowdsale

**Comment by dcxblockchain** [comment]
Hi Igor,

Thanx for the quick responce i figured it out, i did exactly whats on 
the wiki however the endAt of contract1 was overlapping with the 
startsAt of contract2 that's why contract actions where not working.

Maybe add a litte note to the wiki page that time frames cannot overlap 
eachother en there the last tier in crowdsale must be adjsuted first, 
quite logical offcourse, but just one of those things you tent to dont 
think of.

Br
Martijn

Igor Barinov schreef op 2017-12-13 15:10:

**Comment by igorbarinov** [comment]
@hashguide please add mention of this use case to the wiki page
