### ISSUE TITLE
Sending tokens to other Adress: failed transaction

### ISSUE THREAD

**Issue by qweez** [oraclesorg/ico-wizard#403]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten Test Net

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x2171ADE6cCE61694Ed75926EADA5aCE2e8E9d1f2&networkID=3

### Do you have screenshots showing the problem?

Transferring Created Tokens to other addresses Fails.
Any approval within the Contracts fails also. Cant set minting finished function.
Already tried with a ridiculous amount of gas. Any suggestions? Contract is Standard One. 

<img width="938" alt="bildschirmfoto 2017-12-14 um 11 00 41" src="https://user-images.githubusercontent.com/6099879/33986532-1cc2724e-e0be-11e7-8dd3-935b60e5bef5.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No, Errors in DEV. 

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

*Your answer*

---

**Comment by igorbarinov** [comment]
You need to finalize your crowdsale first, please read an article about Finalizing in our wiki

**Comment by qweez** [comment]
thx. working now.
