### ISSUE TITLE
Starting Issues

### ISSUE THREAD

**Issue by indiaprivate** [oraclesorg/ico-wizard#406]
I used the mainnet for deploying my ERC-20 token creation contract. We were proposing a ICO, so I used Orcales Wizard to create tokens. Now, We wish to edit the start date and end date of ICO. The wizard never gave me this option whether this will be editable or not. Can somebody help me check whether it is editable, since I wish to change the start and end date.

Also, the total token supply were kept at 360 million tokens, where 200 million tokens were kept for the team and 160 million are for sale. Now, if we wish to transfer tokens from the 160 million kept for sale can we do it, we understand not 160 million tokens will not be sold, where are these 160 million tokens as of now, can we transfer some coins from this 160 million to a new address?

The link is

https://wizard.oracles.org/invest?addr=0xFf19CAC979d58d0f69d9C181b15CAF1FD1DA5832&networkID=1

**Comment by vbaranov** [comment]
>I used the mainnet for deploying my ERC-20 token creation contract. We were proposing a ICO, so I used Orcales Wizard to create tokens. Now, We wish to edit the start date and end date of ICO. The wizard never gave me this option whether this will be editable or not. Can somebody help me check whether it is editable, since I wish to change the start and end date.

Please, check wiki how to change start/end time: https://github.com/oraclesorg/ico-wizard/wiki/Set-Crowdsale-Start-and-End-Time

>Also, the total token supply were kept at 360 million tokens, where 200 million tokens were kept for the team and 160 million are for sale. Now, if we wish to transfer tokens from the 160 million kept for sale can we do it, we understand not 160 million tokens will not be sold, where are these 160 million tokens as of now, can we transfer some coins from this 160 million to a new address?

If you used reserved tokens functionality, the tokens will be ditributed after crowdsale finalization. Please, check how to finalize: https://github.com/oraclesorg/ico-wizard/wiki/Finalize-crowdsale
