### ISSUE TITLE
Pre-Ico Tiers from White list

### ISSUE THREAD

**Issue by yurieasy** [oraclesorg/ico-wizard#44]
Organiser performs KYC data collection with the White-List from the crowd before starting private Pre-Ico-Tier and pick up a group from the crowd who meet the requirements (could be > 2000 people) to set up Tiers (1, 2 or 3 pre-ico tiers with different params).

Selected group get the private link to the private Pre-ICO-Tier with specified by organiser params of the Tier:

– hard cap;
– min / max check for one investor;
– dates;
– discount.

**Comment by igorbarinov** [comment]
Added to Whitelist with cap
